### ISSUE TITLE
Is there a Docker image available on Docker Hub?

### ISSUE THREAD

**Issue by vitorbaptista** [transferwise/pipelinewise#202]
I'm looking for a pre-built Docker image on Docker Hub to facilitate deploying PipelineWise. Is it available somewhere or, if not, are there any plans on creating one?

**Comment by koszti** [comment]
There is no docker image on docker hub at the moment, but we have plans to create it in the near future.

Currently you need to build image by your own: https://github.com/transferwise/pipelinewise#running-from-docker

**Comment by vitorbaptista** [comment]
Thanks @koszti, let me know if there's something you'd like help with to publish the official image on Docker Hub. Meanwhile, if anyone reads this and would like an image, I just created https://cloud.docker.com/repository/docker/vitorbaptista/pipelinewise/general.
