### ISSUE TITLE
Custom value for batch_size_rows is ignored

### ISSUE THREAD

**Issue by mlavoie-sm360** [transferwise/pipelinewise#208]
### Describe the bug
Modifying the value of `batch_size_rows` does not actually modify the size of each batch on export.

### Steps To Reproduce
1. Modify the `batch_size_rows`
1. Run tap

### Expected behavior
Modifying the value of `batch_size_rows` should modify the size of each batch on export

### Screenshots and log output
https://github.com/transferwise/pipelinewise/blob/ae3bb2a3b7bf7a2b74b129cdac0c253cda03bb91/pipelinewise/cli/samples/tap_mysql_mariadb.yml.sample#L31

https://github.com/transferwise/pipelinewise/blob/ae3bb2a3b7bf7a2b74b129cdac0c253cda03bb91/pipelinewise/fastsync/commons/tap_mysql.py#L15

**Comment by koszti** [comment]
@mlavoie-sm360 `batch_size_rows` is a parameter for the target component and not for the tap.

If you want to customise how many rows should be exported in one batch than put it under `db_conn` in tap mysql YAML.

Updated to the sample file in master https://github.com/transferwise/pipelinewise/blob/master/pipelinewise/cli/samples/tap_mysql_mariadb.yml.sample#L24

**Comment by koszti** [comment]
closing this because it's been fixed for a while and documentation updated
