### ISSUE TITLE
Ungraceful Ctrl-C termination of tap-run keeps in running state.

### ISSUE THREAD

**Issue by johnoscott** [transferwise/pipelinewise#214]
Ungraceful termination. Doing Ctrl-C of run-tap does terminate but when I attempt to run the tap again it fails saying it is in a running state. I tracked down the cause being the last log file keeps its ".running" suffix (which I assume is used as a kind of lock file to prevent concurrent execution). Suggest graceful clean-up of log file to ".cancelled"

**Comment by bparlapalliWiley** [comment]
the only workaround for this is to rename the yaml and re-import with a new ID/name

**Comment by johnoscott** [comment]
actually I was able to workaround this by changing the ".running" suffix of the log file.
