### ISSUE TITLE
Misleading tap-run log message : INFO Schema '<target-schema>' does not exist. Creating... 

### ISSUE THREAD

**Issue by johnoscott** [transferwise/pipelinewise#215]
This is minor, but a bit annoying.

I get a misleading log message for a tap-run targeting Snowflake : 

```INFO Schema 'DEV_APPLYOL' does not exist. Creating... CREATE SCHEMA IF NOT EXISTS DEV_APPLYOL.```

This always shows in each run-tap log.

The schema DOES exist and although the CREATE SCHEMA IF NOT EXISTS is benign, I would prefer if the assertion in the log was accurate.

**Comment by koszti** [comment]
Closing this because it's been fixed for a while.
