### ISSUE TITLE
What happens to history when re-importing configs ?

### ISSUE THREAD

**Issue by johnoscott** [transferwise/pipelinewise#216]
I would like some clarification on what happens when making changes to tap and target configs and re-importing them.

When re-importing config, when does any history, bookmarks etc get erased ? The reason I ask is when I execute a subsequent tap-run, it seems to spend a lot of time checking out the existing tables.

**Comment by koszti** [comment]
When re-importing config it scans every table again and searching column names, types, primary keys, etc. from the DB metadata tables and it takes roughly the same amount of time as the first import.

History and bookmarks are not touched during the re-import. Bookmarks remain the same position of every table and it's safe to re-import project at any time.
