### ISSUE TITLE
Pre-flight checks for tap-run performed during config import

### ISSUE THREAD

**Issue by johnoscott** [transferwise/pipelinewise#221]
Import should pre-flight check for config that will fail when run e.g. replication methods that require a primary key, or tables set to use the logging replication method that do not have logging enabled in the source db. I spent a lot of time understanding cause of failure being the need for a primary key in my source Oracle database.

**Comment by johnoscott** [comment]
I do see `CRITICAL Primary key is set to mandatory but not defined in the [some_schema-some_table] stream` in the tap-run logs, however I am suggesting these checks be done at config import time when the source database is being scanned anyway.

**Comment by koszti** [comment]
fixed by #276 and merged to master

**Comment by johnoscott** [comment]
Awesome. This is a great addition.
