### ISSUE TITLE
Target-snowflake does not create schema and tables with key words

### ISSUE THREAD

**Issue by bparlapalliWiley** [transferwise/pipelinewise#228]
In target snowflake, we cannot create tables or schemas with keyword names
for example:
`Schema name AS failed (created schemas AS AS)`
`Table name ORDER failed (Create table ORDER - ORDER is reserved key word in Snowflake)`

there is a workaround for this and we have got it working - but needs to be tested fully with any other issues.

**Comment by bparlapalliWiley** [comment]
work around:

in
\TransferWise\pipelinewise\pipelinewise\fastsync\commons\target_snowflake.py

replace all
`CREATE OR REPLACE TABLE {}.{} ({}`

with
`CREATE OR REPLACE TABLE \"{}\".\"{}\" (\"{}\"`

**Comment by EamonKeane** [comment]
fwiw, the snippet below seems to work with the current version of target_snowflake.py.

`        columns_string = ""
        for c in columns:
            columns_string = columns_string + '"' + c.split()[0].upper() + '" ' + c.split()[1] + ","

        sql = """CREATE OR REPLACE TABLE {}.{} ({} PRIMARY KEY (\"{}\"))
        """.format(target_schema, target_table, columns_string, primary_key.upper())
        self.query(sql)`

**Comment by EamonKeane** [comment]
I think this has now been fixed in 0.13.1

**Comment by koszti** [comment]
Using reserved words as table and column names has been fixed across every tap and target connectors. It's available in master and soon in PPW 0.16.0 release.
