### ISSUE TITLE
Snowflake-connector-python update needed?

### ISSUE THREAD

**Issue by lauriounmaa** [transferwise/pipelinewise#233]
When using Snowflake as a target I am getting an error:

CRITICAL: asn1crypto.keys.PublicKeyInfo().unwrap() has been removed, please use oscrypto.asymmetric.PublicKey().unwrap() instead

Snowflake updated their connector recently:
https://www.snowflake.com/blog/latest-changes-to-how-snowflake-handles-ocsp/

https://pypi.org/project/snowflake-connector-python/
> v2.0.1(October 04,2019)

> Add asn1crypto requirement to mitigate incompatibility change

**Comment by guy-adams** [comment]
I found the same thing today and created a pull request:
 https://github.com/transferwise/pipelinewise-target-snowflake/pull/30

**Comment by koszti** [comment]
thanks for this, this looks quite urgent. I'm just wondering why we don't experience this in our snowflake account in eu-central-1. Do you know if this related to snowflake accounts in different regions maybe and release schedule is not in sync in every region?


Based on `select CURRENT_VERSION();` eu-central-1 is on 3.45.1 and not having this problem (yet).

**Comment by lauriounmaa** [comment]
Region eu-west-1 and it is also on 3.45.1 so this might not be it.
Noticed that we were able to run the  pipelines only by changing the connector version in pipelinewise main code without changing the target.

**Comment by guy-adams** [comment]
I've tested multiple tenants on eu-west-1 and all on 3.45.1 so not sure why some poeple are seeing this and some aren't. I ran the same test multiple times and always got the same result. 

@lauriounmaa - what did you change the connector version to to allow this to start working? I had thought that pipelinewise was using the latest version of the target-snowflake and therefore the target-snowflake itself had to be bumped?

**Comment by koszti** [comment]
Please note there are two snowflake connectors. One in the main pipelinewise repo to do the FULL_TABLE [FastSync] (https://transferwise.github.io/pipelinewise/user_guide/fastsync.html) to snowflake and one in [target-snowflake](https://github.com/transferwise/pipelinewise-target-snowflake) to do singer INCREMENTAL and LOG_BASED. Both of them using an elder version of snowflake connector and both need to be updated to the latest version.

target-snowflake is running `insecure_mode` (https://github.com/transferwise/pipelinewise-target-snowflake/blob/master/target_snowflake/db_sync.py#L290) to avoid OCSP issues but the main pipelinewise is not using this option: https://github.com/transferwise/pipelinewise/blob/master/pipelinewise/fastsync/commons/target_snowflake.py#L23 . Maybe we have this problem only if the table is replicated with FULL_TABLE method when secure mode is turned on (???).

Anyways, both components will be upgraded to the latest 2.0.1 very soon with secure mode enabled.

**Comment by koszti** [comment]
Addressed by:
* In main pipelinewise for FULL_TABLE FastSync: https://github.com/transferwise/pipelinewise/pull/235
* in target-snowflake for singer INCREMENTAL and LOG_BASED replications: https://github.com/transferwise/pipelinewise-target-snowflake/commit/df46ca85512f659d008c2c568166640cc15a52ef

A new pipelinewise-target-snowflake version (1.0.10) will be released soon on PyPI and will be linked to this main repo to use the latest snowflake-connector across every component.

**Comment by guy-adams** [comment]
@koszti - thanks for the quick response on this. Looking at:

https://github.com/transferwise/pipelinewise-target-snowflake/releases
 
the latest version still seems to be 1.0.9? Should it have updated yet?

**Comment by koszti** [comment]
@guy-adams pipelinewise-target-snowflake-1.1.0 has been released today with the latest snowflake connector and some other improvements.

v1.1.0 is linked to the main pipelinewise repository and now we use snowflake driver 2.0.1 everywhere in the code. I hope this helps.
