### ISSUE TITLE
MySQL taps white space in either table or column names breaks

### ISSUE THREAD

**Issue by guy-adams** [transferwise/pipelinewise#242]
Both of these are allowed in ANSI SQL.

To fix all MySQL queries need to have the table and column names correctly quoted. Similarly the writes into the target need to be similarly quoted. This should also fix #228 since the quoting required for allowing columns with names that are Reserved words (like Group).

I plan to issue a pull request for the fix for this.

**Comment by koszti** [comment]
@guy-adams please be careful with quoting column names, especially on the target-snowflake side. We want to keep the not case sensitive SQL behaviour in every target so all the below SQL should give the same result:
`SELECT columnone FROM myschame.MYTABLE`
`SELECT columnOne FROM myschame.myTable`
`SELECT COLUMNone FROM myschame.MyTaBlE`

If we quote to the table and column names in target then probably we need to use it in every SQL (`SELECT * FROM myschema."myTable"`). This is not a great experience when writing queries in the DWH.

Related to https://github.com/transferwise/pipelinewise/pull/243

**Comment by guy-adams** [comment]
@koszti - that makes sense - and in fact with this pull request in place I actually managed to break something of my own by breaking a query to snowflake that used to work due to forcing case. It may be the way that I have solved it is not the right way. None the less I believe pipelinewise should be able to handle source tables and columns with whitespace. The other option is to simply remove the whitespace and replacing with a "-" or "_" or just removing entirely and having the words run together? This creates slightly undesirable behavious where the target tables have different names to the source tables, but this is still better than not ingesting them at all. What are your thoughts?

**Comment by koszti** [comment]
Yes, I agree, I think replacing whitespaces to "-" or "_" makes sense. Furthermore that doesn't need quoted object names and should not break the current query behaviour in the targets.

Btw, using `_` (underscore) and not `-` is maybe better. Minus signs in object names I think needs to be quoted but underscores are fine.

**Comment by MihalisW** [comment]
In the case of reserved keywords how about dealing with them by appending an `_` (underscore), rather than quoting them?

**Comment by koszti** [comment]
you mean adding an `_` (underscore) prefix or postfix to the colum names? i.e. `SELECT order_ FROM mytable` ?

**Comment by MihalisW** [comment]
Yep, that's correct.

**Comment by guy-adams** [comment]
The only issue I see with this is that it requires us to define an explict list of reserved words rather than "just escape everything" - this may not be an issue, it just gives something that needs to be maintained per target

**Comment by koszti** [comment]
Using reserved words as table and column names has been fixed across every tap and target connectors. It's available in master and soon in PPW 0.16.0 release.
