### ISSUE TITLE
Is scheduling supported?

### ISSUE THREAD

**Issue by guy-adams** [transferwise/pipelinewise#252]
I was under the impression that scheduling of pipeline executions is left to external systems (which is fine with me!). Several places in the documentation:

e.g. pipelinewise/docs/installation_guide/creating_pipelines.rst
https://github.com/transferwise/pipelinewise/search?q=sync_period&unscoped_q=sync_period

have references to a sync_period on cron format that could cause confusion

**Comment by koszti** [comment]
Thank you for this. You're right, scheduling is a task for external systems. It remained in the code for historical reasons. Fixed and removed every `sync_period` reference by https://github.com/transferwise/pipelinewise/commit/04303d8a4f072daeb7062365e04f45305960fb13
