### ISSUE TITLE
target NoneType issue with discover_tap 

### ISSUE THREAD

**Issue by dustymaxa** [transferwise/pipelinewise#289]
`discover_tap` crashs with specified tap and target. It seems that the _run_post_import_tap_checks_ has a NoneType target..

command : `discover_tap --tap test_mysql_mysql_mariadb --target my_test_snowflake
`
My tap and target exist and have the correct id specified in the yaml config.

`Traceback (most recent call last):
  File "/app/.virtualenvs/pipelinewise/bin/pipelinewise", line 11, in <module>
    load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')()
  File "/app/pipelinewise/cli/__init__.py", line 109, in main
    getattr(pipelinewise, args.command)()
  File "/app/pipelinewise/cli/pipelinewise.py", line 630, in discover_tap
    post_import_errors = self._run_post_import_tap_checks(schema_with_diff, target)
  File "/app/pipelinewise/cli/pipelinewise.py", line 1229, in _run_post_import_tap_checks
    primary_key_required = target.get("primary_key_required", False)
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by koszti** [comment]
seems like this is bug and I could also reproduce. The target dict not passed correctly to the discovery method and later to `_run_post_import_tap_checks`

For the time being you can reimport the entire project the will discover every tap automatically and that seems to be working with the command `pipelinewise import --dir <project-dir-with-yaml-files>`

**Comment by dustymaxa** [comment]
Hi @koszti ,

I still have issues with the discover_tap command. Here is my command and the output.
 
`pipelinewise discover_tap --tap my_sales_mysql_mariadb --target my_test_snowflake
`

` File "/app/.virtualenvs/pipelinewise/bin/pipelinewise", line 11, in <module>
    load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')()
  File "/app/pipelinewise/cli/__init__.py", line 108, in main
    pipelinewise = PipelineWise(args, config_dir, venv_dir)
  File "/app/pipelinewise/cli/pipelinewise.py", line 74, in __init__
    self.tap = self.get_tap(args.target, args.tap)
  File "/app/pipelinewise/cli/pipelinewise.py", line 327, in get_tap
    taps = self.get_taps(target_id)
  File "/app/pipelinewise/cli/pipelinewise.py", line 311, in get_taps
    target = self.get_target(target_id)
  File "/app/pipelinewise/cli/pipelinewise.py", line 299, in get_target
    raise Exception(f"Cannot find {target_id} target")
Exception: Cannot find my_test_snowflake target
`

My tap and target exist and have the correct id specified in the yaml config.

Thanks
