### ISSUE TITLE
Binary mysql-snowflake fast-sync reverted in 12.2 pylint fix

### ISSUE THREAD

**Issue by EamonKeane** [transferwise/pipelinewise#321]
I think this issue inadvertently changed `binary: 'BINARY'` back to `binary: 'VARCHAR'`. https://github.com/transferwise/pipelinewise/commit/3aa15a03931d2badd8d444a3bab9e0898c27aec6#diff-cb69f4bfe2a71a1cc8b2301f40ac0fa0R43

**Comment by koszti** [comment]
thanks @EamonKeane reporting this. https://github.com/transferwise/pipelinewise/pull/322 fixing it and merged to master. We'll release a new version with the fix (0.12.3) in a couple of days.
