### ISSUE TITLE
Why "compatible" taps and targets?

### ISSUE THREAD

**Issue by jazzido** [transferwise/pipelinewise#336]
Hi,

I'm familiar with Singer, and I'm starting to explore PipelineWise. 

Couldn't find any information about this in the documentation, so I thought I might ask: what does a tap or target need to support in order to make it "compatible" with PipelineWise?

Thanks!

**Comment by koszti** [comment]
hey, the contribution section in the documentation has some info about taps and target compatibility: https://transferwise.github.io/pipelinewise/project/contribution.html#contribution

**Comment by koszti** [comment]
We recently added another detailed contribution docs at https://github.com/transferwise/pipelinewise/blob/master/CONTRIBUTING.md . This one and the previous link in the docs should give enough details about pipelinewise compatibility and contributing, if you want to ;) - in general.

I hope this help.
