### ISSUE TITLE
Function safe_column_name in util.py :'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by ReptilianBrain** [transferwise/pipelinewise#338]
I'm getting this error I think when tap_msql.py is doing the map_column_types_to_target method and the primary key from "self.get_primary_key" is None. 

The get_primary_key method seems to be allowed to return None so i'm guessing there a conflict here for syncing table without a primary key.

**Comment by koszti** [comment]
@ReptilianBrain https://github.com/transferwise/pipelinewise/pull/340 fixed this and available in master and in the latest 0.13.3

**Comment by ReptilianBrain** [comment]
Thank you very much for looking into this
