### ISSUE TITLE
mysql to snowflake fastsync doesn't work with IAM role

### ISSUE THREAD

**Issue by mashanm** [transferwise/pipelinewise#351]
mysql_to_snowflake connector doesn't work with IAM roles. Fails with below error.

> logger_name=pipelinewise.cli.pipelinewise log_level=INFO process_name=MainProcess file_name=pipelinewise.py line_no=(868) message=Exception: Config is missing required keys: ['aws_access_key_id', 'aws_secret_access_key']

**Comment by koszti** [comment]
IAM roles currently not supported in fastsync(s) for snowflake and redshift.

There is a pending/WiP PR to address this for redshift: https://github.com/transferwise/pipelinewise/pull/285/files  and we'll need something very similar for snowflake as well.

**Comment by mashanm** [comment]
Opened [this](https://github.com/transferwise/pipelinewise/pull/357 ) PR to address this. 
Unable to link the PR by myself.
