### ISSUE TITLE
psycopg2-binary instead of psycopg2

### ISSUE THREAD

**Issue by madpin** [transferwise/pipelinewise#362]
Hello,

I`m having this problem because in our system it's being painfully to install psycopg2, there is any major reason why not use psycopg2-binary in the tap and target?

Of course, I volunteer for doing the change, just want to understand if there is any other reason why use psycopg2 instead of psycopg2-binary.

Thanks,

**Comment by koszti** [comment]
hey @madpin , I remember somebody else also asked this a while ago. Actually the only reason is the comment in the psychopg doc at https://www.psycopg.org/docs/install.html#binary-install-from-pypi:

> Note The psycopg2-binary package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements.
> If you are the maintainer of a publish package depending on psycopg2 you shouldn’t use ‘psycopg2- binary’ as a module dependency. For production use you are advised to use the source distribution.

TBH I don't know how relevant is this, I can see many large projects are using psycopg2-binary and I don't think it would cause any troubles. Can you please go ahead, try and share your thoughts and experiences with it? PRs are welcome :)

**Comment by koszti** [comment]
we switch to `psycopg2-binary` and it's available in master and soon in PPW 0.16.0 release.
