### ISSUE TITLE
Dockerfile build broken

### ISSUE THREAD

**Issue by andrevtg** [transferwise/pipelinewise#393]
Some dependencies got messed up very recently (build worked fine a few days ago):

    --------------------------------------------------------------------------
    Installing target-snowflake connector...
    --------------------------------------------------------------------------
    ....
    pipelinewise-singer-python 1.1.1 has requirement pytz==2019.3, but you have pytz 2020.1.

Removing the snowflake connector solved the issue:
In setup.py under install_requires:

    #'snowflake-connector-python==2.0.3',

And install.sh under DEFAULT_CONNECTORS:

    #    target-snowflake

**Comment by koszti** [comment]
fixed in the downstream pipelinewise-singer-python by https://github.com/transferwise/pipelinewise-singer-python/pull/12
