### ISSUE TITLE
S3 Target - support profile based authentication

### ISSUE THREAD

**Issue by asksmruti** [transferwise/pipelinewise#401]
Dear Team,

Is it possible to implement AWS profile or assume role based authentication for S3 target.
Right now, it seems that  it picks hard coded credentials.

aws_access_key_id: "<ACCESS_KEY>"             # S3 - Plain string or vault encrypted
aws_secret_access_key: "<SECRET_ACCESS_KEY>"  # S3 - Plain string or vault encrypted

**Comment by koszti** [comment]
PR #492 created to address it.

**Comment by koszti** [comment]
PR #492 fixed it
