### ISSUE TITLE
Certain invalid characters break MySQL -> Redshift load due to Redshift error

### ISSUE THREAD

**Issue by boringusername99** [transferwise/pipelinewise#405]
I'm getting this error in stl_load_errors after a failed MyQL to Redshift fast sync.
Missing newline: Unexpected character 0x64 found at location 233                                    

I'm already using these copy options (added ACCEPTINVCHARS), but it didn't help.
`copy_options: "EMPTYASNULL BLANKSASNULL TRIMBLANKS TRUNCATECOLUMNS ACCEPTINVCHARS TIMEFORMAT 'auto'"`

Looking at the character in question, it looks like a hacker was trying to do some code injection on our site, leading to this invalid character. I've obfuscated some data in my log output here, but position 233 is actually after the end of the raw_line returned by Redshift. I would have to go back to the raw S3 file to see what is actually there.

`2737626,1434,2019-07-03,2,38,http://xxxxxxxxx.xxxxxxx.com/xxxxx/xxxx.php?id=1434&group=38&subid=/etc/passwd%00http://xxxxx.xxxxx.com/xxxxx/xxxxxxx.php?id=1434&group=38&subid=%2fetc%2fpasswd%00,"/etc/passwd`

I'm not sure the best path here, but it seems like either having Pipelinewise filter out these characters during export from MySQL, or passing different options to Redshift so it can proceed more gracefully.

**Comment by ReptilianBrain** [comment]
Hi @boringusername99.

We had a similar situation to what you are currently describing. 

We also tough that adding ACCEPTINVCHARS would help us during the copy operation. After some test we went with this option instead:  NULL AS '\\0'.

I'm not 100% sure why but by replacing ACCEPTINVCHARS with NULL AS '\\0'  we were able to sync the table. Might worth a shot ?

**Comment by boringusername99** [comment]
Thanks. That helped, and seemed to solve that particular issue. I actually used both options together, but it may be that just NULL AS '\0' would have been enough.
