### ISSUE TITLE
how to elt view or rename table from mysql to postgres?

### ISSUE THREAD

**Issue by dangvanduc90** [transferwise/pipelinewise#443]
i have 2 tap mysql at 2 ip,
all of they have users, how can i rename users table at one tap or i will clone users table to view ex: users_view. how can i etl view to postgresql target

**Comment by koszti** [comment]
I'm not sure if I understand correctly. Basically the table names in the targets are generated automatically and always the same as it appears in the source.

If you two taps and both of them have the table with the same name, then you need to define two different `target_schema` in the two tap YAMLs and load into two different schemas.

ELT-ing views from source to target works like normal tables, but you can use only `FULL_TABLE` and `INCREMENTAL` methods. Views will be normal tables in target.
