### ISSUE TITLE
tap gets stuck

### ISSUE THREAD

**Issue by hardik1986** [transferwise/pipelinewise#452]
### Subject of the issue
I have created tap-jira and target-postgres for my Jira instance. It was working great for straight two months but one day I stopped seeing new data coming in(jira issue updates). I noticed the run_tap was stuck on below. I tried multiple times to stop and start the tap but still it gets stuck. I have issue table select in tap-jira.yaml. I would appreciate any help to debug this.

INFO METRIC: {"type": "counter", "metric": "record_count", "value": 50, "tags": {"endpoint": "issues"}}
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 8.2039155960083, "tags": {"endpoint": "issues", "http_status_code": 200, "status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 50, "tags": {"endpoint": "issues"}}
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 8.22981882095337, "tags": {"endpoint": "issues", "http_status_code": 200, "status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 50, "tags": {"endpoint": "issues"}}
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 8.420924186706543, "tags": {"endpoint": "issues", "http_status_code": 200, "status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 50, "tags": {"endpoint": "issues"}}

### Your environment
* Version of PipelineWise, e.g branch/commit #/release/tag - 0.16(latest)
* Source type and setup - Jira 
* Target type and setup - Poastgres

### Steps to reproduce
pipelinewise run_tap --tap jira --target postgres_dwh 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Further notes
Tell us why you think this might be happening, or stuff you tried that didn't work

**Comment by EamonKeane** [comment]
No particular insights into that issue but you should try.

`pipelinewise run_tap --tap jira --target postgres_dwh --debug --extra_log`

**Comment by Samira-El** [comment]
Hey, are you sure the source API has any new data to consume? It might seem stuck but it could be that there is no new data to stream.

**Comment by hardik1986** [comment]
thank you guys for replying. @EamonKeane  I already tried with --extra_log and it did not display anything different from log folder. @Samira-El  I confirmed that there is new data. I noticed that it always stops at 65200 rows but in our Jira instance, there are 150k+ issues. I took advantage of Stitchdata free trial and configured exactly the same and no luck. It errored out on stitchdata too at same place. At least Stitchdata was giving this error:
2020-06-29 16:47:46,616Z    tap - ERROR Backing off send(...) for 8.0s (requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))) 

any idea what is this about? i googled this error and only useful thing found is some user suggesting below:
I had a similar problem while making post requests in a for loop, which run 400 times, each loop run with two requests and a last request after exiting the loop. I found out while making API requests the server (check_mk) was not ready, still compiling some hots and service data. So I placed the time.sleep() just before the each request and that fixed the problem. I don't know how often you make the requests but I'd try it this way

source: https://stackoverflow.com/questions/52051989/requests-exceptions-connectionerror-connection-aborted-connectionreseterro

**Comment by EamonKeane** [comment]
@hardik1986 the variable in question might be here if you haven't seen it. So you'd need to fork it and try increase maybe.

https://github.com/singer-io/tap-jira/blob/65963ff460b6d098a9a3e1f415d24eb27a867468/spikes/issues-fields-envelope-unwrapping/looking_at_issues_and_fields.py#L15

`TIME_BETWEEN_REQUESTS = timedelta(microseconds=10e3)`

**Comment by hardik1986** [comment]
@EamonKeane thanks I will look into it. Also I think missed your comment of --debug flag. Only tried --extra_log. Let me try debug flag too.

**Comment by hardik1986** [comment]
> @hardik1986 the variable in question might be here if you haven't seen it. So you'd need to fork it and try increase maybe.
> 
> https://github.com/singer-io/tap-jira/blob/65963ff460b6d098a9a3e1f415d24eb27a867468/spikes/issues-fields-envelope-unwrapping/looking_at_issues_and_fields.py#L15
> 
> `TIME_BETWEEN_REQUESTS = timedelta(microseconds=10e3)`

@EamonKeane any idea how do I bring this to pipelinewise setup? this seems to be singer repo but I setup the pipelinewise thru source.

**Comment by Samira-El** [comment]
Once you fork tap-jira and make the changes, update the requirement [here](https://github.com/transferwise/pipelinewise/blob/master/singer-connectors/tap-jira/requirements.txt) to point to your forked github repo and run install.

**Comment by koszti** [comment]
@hardik1986 just wondering, did you have any luck by adjusting `TIME_BETWEEN_REQUESTS`? If yes, then maybe we can consider making this parameter configurable and send PR to the original singer repo, or alternatively we can create an "official" pipelinewise-tap-jira fork with this change. Maybe other people have the same problem. What do you think?

**Comment by hardik1986** [comment]
Sorry for late reply but I had no luck and gave up on this :( Hopefully singer fixes tap-jira in future.
