### ISSUE TITLE
Logging, monitoring and alerting best practices?

### ISSUE THREAD

**Issue by henriblancke** [transferwise/pipelinewise#465]
## Subject of the issue
I'd like to better understand how others have:
1. Made pipelinewise work with their logging setup/infrastructure?
2. How you're using your logs to monitor taps and alert when things go wrong?

So far, I've noticed the following with the default logging configuration:

### Run summary
The run summary - although it's great - is multi-line. That makes parsing it with external log collection tools like datadog difficult (without losing context like time, etc.).

### Running without `--extra_log`
Running a tap without `--extra_log` gives little information. You don't get much context when running into an issue or error.

#### Logs
Running a tap with `--extra_log` gives you a ton of information, often too much. For `tap-salesforce` for example, it logs multiple lines for each transformation; blowing up the logs and potentially adding $$ when used with volume-based log collection systems. For `tap-mysql`, information_schema queries get logged and they are often multi-line, making the logs difficult to parse and losing context. 

#### Metrics
Certain taps log metrics when `--extra_log` is set. Metrics are logged in a JSON formatted string that is part of the default key-value formatted logging string, making it more difficult to parse and structure them.

#### State file updates
With `--extra_log` set, some taps seem to log the updated state JSON as part of key-value formatted string.

## Question
How have you dealt with integrating pipelinewise logs into external log collection tools or your internal log collection setup? What kind of information were you able to extract for monitoring purposes and how have you set up alerting? 

An option I'm exploring is to use [jsonformatter](https://pypi.org/project/jsonformatter/#:~:text=LogRecord%20Attributes-,jsonformatter%20%2D%2D%20for%20python%20log%20json,are%20supported%20from%20version%200.2.) in combination with `logging.conf`. That could resolve the multi-line issue described above? When trying to use the Dockerfile and installation procedure included in this project, `jsonformatter` would have to be installed in each pyenv created for each installed tap. We could definitely make that happen, but I wanted to reach out first and make sure I'm not overlooking something? Thanks for your help!

We've been very amazed by the pipelinewise / singer framework and are actively working towards using it in production at my company! Logging, alerting, etc is the last piece of the puzzle 🎉 . Thanks for making this amazing project available and for making our lives easier!

**Comment by koszti** [comment]
hey, thanks for the feedback.

Basically you’re right in every point. Improving logging and alerting are one of the items from top of our list. 

Actually we feel the same pain that you detailed, especially with multiline logs. We’re planning to do some log consolidation across the connectors and review what do we log and how, especially the SQL queries. Currently we’re trying to ship the logs to ELK but well..,like you said it’s not always in a consumable format. I personally don’t know the jsonformatter that you mentioned. Probably worth to explore the capabilities, thanks!

Regarding alerting we are planning to add a hopefully generic and configurable webhook based notification option. In the first round we want to focus on slack integration but rollbar, victorops and senity also mentioned.

Nothing guaranteed but there is a very good chance to see some progress on this front in the near future. ;)

**Comment by henriblancke** [comment]
That is great to hear! Very exciting stuff 🚀 . If there is anything we can help with for this effort let me know!

**Comment by koszti** [comment]
https://github.com/transferwise/pipelinewise/pull/467 has been merged to master that adds alerting capabilities to slack.

Alerting is an undocumented feature until the next PPW release but if you need to send alerts to an external system please check how the [SlackAlertHandler](https://github.com/transferwise/pipelinewise/blob/master/pipelinewise/cli/alert_handlers/slack_alert_handler.py) implemented in the PR above and please send a new PR.

**Comment by Samira-El** [comment]
Hey, re the logging, I concur that some taps are logging too much for the info level, as Peter said, we plan on reviewing what we log in every connector that we maintain.

I would like to add that it's possible for you to provide your own custom logging configuration with the help of the env var `LOGGING _CONF_FILE` which you can point to some `logging.conf` file thus helping you override PipelineWise and the connectors' config.
Hope this helps!
