### ISSUE TITLE
Question about submodule and accessing tap/target.yml configuration files from internal repo

### ISSUE THREAD

**Issue by lucaswiley** [transferwise/pipelinewise#491]
### Subject of the issue
Hi there. I have a specific question about the install process. When Pipelinewise is installed, it is installed in my repository as a submodule that points to this `transferwise/pipelinewise` repository. That is fine, however I want to be able to have my configuration files e.g. `tap_postgres.yml` stored in my primary repository so they can be modified from a text editor. 

(Note: I am not worried about confidential database connection information being stored in Github because each of the values points to an environment variable on the machine.)

Is there a way to do this?

Perhaps this is more my misunderstanding of Git rather than anything with this repo. 

### Your environment
* PipelineWise 0.20.2 - Command Line Interface
* Postgres
* Snowflake

### Steps to reproduce
You would do an install on your machine (local or server). Then when you `cd ..` to primary project repository (not pipelinewise) and commit the changes, they will commit to the pipelinewise submodule without displaying the information from the tap/target.yml configuration files. 

Commit hash: https://github.com/transferwise/pipelinewise/tree/30571f4c1b16171b409869548574e3f164ee17de, which was not pushed to the remote, holds the configuration files. 

### Expected behaviour
Ideally these .yml config files are accessible from the primary repository (my working repo not `/pipelinewise`). 

### Actual behaviour
Files are seemingly committed towards `transferwise/pipelinewise` but I cannot push to the repo as I am not a contributor, nor would I likely want to. 

### Further notes
I have tried both installing Pipelinewise via Docker, Source, and using `git submodule add https://github.com/transferwise/pipelinewise.git`. 

Thanks!

**Comment by Samira-El** [comment]
Hey Lucas, this sounds like a confusion caused by Git, I haven't tried git submodules before so I cannot say if it is what's causing this behavior.

In our setup, we have pipelinewise installed via source in one repo and the taps/targets live in another repo, which if I understood this issue is what you're trying to achieve, you then need to point pipelinewise to these config files by the command `pipelinewise import --dir /path/to/congif_files`. 

Let me know how it goes!

**Comment by lucaswiley** [comment]
Hi Samira. Yes you are right that was easy enough. I just moved the configuration files created from `pipelinewise init --name some_dir_name` higher up into the parent directory and imported from that path. 

My initial thought was that `some_dir_name` with configs had to sit within the `pipelinewise/` directory but that doesn't seem to matter. 

Thanks for your quick response.
