### ISSUE TITLE
Google Analytics Tap - Custom Report

### ISSUE THREAD

**Issue by dustymaxa** [transferwise/pipelinewise#502]
Question:

Is it possible to specify a report.json file in the google analytics yaml tap? As I understand it's only possible for now to sync default reports (https://github.com/transferwise/pipelinewise-tap-google-analytics/blob/master/tap_google_analytics/defaults/default_report_definition.json)

The example of how to use report parameter with google analytics tap: https://gitlab.com/meltano/tap-google-analytics#optional-parameters

Thanks,

Dusty

**Comment by Samira-El** [comment]
Hey,
Thanks for you patience!

It seems like it is possible to supplement your own reports, from the tap's readme:
```
To that end, this tap uses an additional JSON file for the definition of the reports that the user wants to be generated. You can check, as an example, the JSON file used as a default in tap-google-analytics/defaults/default_report_definition.json. Those report definitions could be part of the `config.json`, but we prefer to keep config.json small and clean and provide the definitions by using an additional file.
```

So you can point to another reports by having the setting `reports` to the path of your file in the tap's `db_conn` section.
