### ISSUE TITLE
NoneType object has no attribute 'settimeout' when INCREMENTAL large database

### ISSUE THREAD

**Issue by dangvanduc90** [transferwise/pipelinewise#503]
when i INCREMENTAL table `users` with `replication_key` set to `id`
from `mysql` to `postgresql` i got failed.
this is log i got:

time=2020-08-06 11:30:00 logger_name=tap_mysql log_level=INFO message=Server Parameters: version: 5.7.23-log, wait_timeout: 28800, innodb_lock_wait_timeout: 3600, max_allowed_packet: 4194304, interactive_timeout: 28800
time=2020-08-06 11:30:00 logger_name=tap_mysql log_level=INFO message=Server SSL Parameters(blank means SSL is not active): [ssl_version: ], [ssl_cipher: ]
time=2020-08-06 11:30:01 logger_name=tap_mysql log_level=INFO message=Beginning sync for InnoDB table auth_ws.users
time=2020-08-06 11:30:01 logger_name=tap_mysql log_level=INFO message=Stream auth_ws-users is using incremental replication
time=2020-08-06 11:30:01 logger_name=target_postgres log_level=INFO message=TARGET_POSTGRES - Running query: SELECT LOWER(schema_name) schema_name FROM information_schema.schemata WHERE LOWER(schema_name) = %s
time=2020-08-06 11:30:01 logger_name=target_postgres log_level=INFO message=TARGET_POSTGRES - Running query: SELECT table_name FROM information_schema.tables WHERE table_schema = %s
time=2020-08-06 11:30:01 logger_name=target_postgres log_level=INFO message=Table 'users' exists
time=2020-08-06 11:30:01 logger_name=target_postgres log_level=INFO message=TARGET_POSTGRES - Running query: SELECT column_name, data_type
      FROM information_schema.columns
      WHERE lower(table_name) = %s AND lower(table_schema) = %s
time=2020-08-06 11:30:02 logger_name=tap_mysql log_level=INFO message=Running SELECT `social_image_first`,`vg_token`,`name`,`remark`,`certified_at`,`password`,`certified_by`,`phone`,`social_id`,`support_note`,`parent_id`,`address`,`id`,`created_at`,`remember_token`,`last_login_at`,`email`,`is_email_verified`,`username`,`district_id`,`lvl`,`prev_stat`,`social_image`,`salt_login`,`city_id`,`salt`,`vg_id`,`bod`,`stat`,`social_image_last`,`is_phone_verified`,`updated_at`,`google_id`,`type`,`is_migrated`,`wait_verify_at`,`facebook_id`,`gender` FROM `auth_ws`.`users` WHERE `id` >= 1630211 ORDER BY `id` ASC
time=2020-08-06 11:30:30 logger_name=target_postgres log_level=INFO message=Loading 20000 rows into 'public.users'
time=2020-08-06 11:30:30 logger_name=target_postgres log_level=INFO message=COPY tmp_a55379b0_a47d_42b4_bfd5_5d57fdc3286b ("_sdc_batched_at", "_sdc_deleted_at", "_sdc_extracted_at", "address", "bod", "certified_at", "certified_by", "city_id", "created_at", "district_id", "email", "facebook_id", "gender", "google_id", "id", "is_email_verified", "is_migrated", "is_phone_verified", "last_login_at", "lvl", "name", "parent_id", "password", "phone", "prev_stat", "remark", "remember_token", "salt", "salt_login", "social_id", "social_image", "social_image_first", "social_image_last", "stat", "support_note", "type", "updated_at", "username", "vg_id", "vg_token", "wait_verify_at") FROM STDIN WITH (FORMAT CSV, ESCAPE '\')
time=2020-08-06 11:35:23 logger_name=target_postgres log_level=INFO message=UPDATE 20000
time=2020-08-06 11:35:23 logger_name=target_postgres log_level=INFO message=INSERT 0 0
time=2020-08-06 11:35:23 logger_name=singer log_level=INFO message=METRIC: {"type": "counter", "metric": "record_count", "value": 20329, "tags": {"database": "auth_ws", "table": "users"}}
time=2020-08-06 11:35:24 logger_name=singer log_level=INFO message=METRIC: {"type": "counter", "metric": "record_count", "value": 1024, "tags": {"database": "auth_ws", "table": "users"}}
time=2020-08-06 11:35:24 logger_name=singer log_level=INFO message=METRIC: {"type": "timer", "metric": "job_duration", "value": 322.81113743782043, "tags": {"job_type": "sync_table", "database": "auth_ws", "table": "users", "status": "failed"}}
time=2020-08-06 11:35:24 logger_name=tap_mysql log_level=CRITICAL message='NoneType' object has no attribute 'settimeout'
Traceback (most recent call last):
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1021, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/sync_strategies/incremental.py", line 74, in sync_table
    params)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/sync_strategies/common.py", line 207, in sync_query
    row = cursor.fetchone()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/cursors.py", line 452, in fetchone
    row = self.read_next()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/cursors.py", line 447, in read_next
    return self._conv_row(self._result._read_rowdata_packet_unbuffered())
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1421, in _read_rowdata_packet_unbuffered
    packet = self.connection._read_packet()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1004, in _read_packet
    recv_data = self._read_bytes(bytes_to_read)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1029, in _read_bytes
    "Lost connection to MySQL server during query (%s)" % (e,))
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.virtualenvs/tap-mysql/bin/tap-mysql", line 8, in <module>
    sys.exit(main())
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 712, in main
    raise exc
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 709, in main
    main_impl()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 702, in main_impl
    do_sync(mysql_conn, args.config, catalog, state)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 653, in do_sync
    sync_non_binlog_streams(mysql_conn, non_binlog_catalog, config, state)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 628, in sync_non_binlog_streams
    do_sync_incremental(mysql_conn, catalog_entry, state, columns)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 507, in do_sync_incremental
    incremental.sync_table(mysql_conn, catalog_entry, state, columns)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/sync_strategies/incremental.py", line 74, in sync_table
    params)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/cursors.py", line 67, in __exit__
    self.close()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/cursors.py", line 427, in close
    self._result._finish_unbuffered_query()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1438, in _finish_unbuffered_query
    packet = self.connection._read_packet()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 987, in _read_packet
    packet_header = self._read_bytes(4)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1018, in _read_bytes
    self._sock.settimeout(self._read_timeout)
AttributeError: 'NoneType' object has no attribute 'settimeout'
Exception ignored in: <function MySQLResult.__del__ at 0x7f8461075dd0>
Traceback (most recent call last):
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1336, in __del__
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1438, in _finish_unbuffered_query
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 987, in _read_packet
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1018, in _read_bytes
AttributeError: 'NoneType' object has no attribute 'settimeout'
time=2020-08-06 11:35:25 logger_name=transform_field log_level=INFO message=Exiting normally
time=2020-08-06 11:35:25 logger_name=target_postgres log_level=INFO message=Loading 1353 rows into 'public.users'
time=2020-08-06 11:35:25 logger_name=target_postgres log_level=INFO message=COPY tmp_e3034fe3_c36a_4486_be3d_974d44673441 ("_sdc_batched_at", "_sdc_deleted_at", "_sdc_extracted_at", "address", "bod", "certified_at", "certified_by", "city_id", "created_at", "district_id", "email", "facebook_id", "gender", "google_id", "id", "is_email_verified", "is_migrated", "is_phone_verified", "last_login_at", "lvl", "name", "parent_id", "password", "phone", "prev_stat", "remark", "remember_token", "salt", "salt_login", "social_id", "social_image", "social_image_first", "social_image_last", "stat", "support_note", "type", "updated_at", "username", "vg_id", "vg_token", "wait_verify_at") FROM STDIN WITH (FORMAT CSV, ESCAPE '\')

**Comment by koszti** [comment]
The real problem is this one: `pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')`. This error appears when the connection between your MySQL client and database server times out. Essentially, it took too long for this query to return data so the connection gets dropped:

```
SELECT <columns> FROM auth_ws.users WHERE id >= 1630211 ORDER BY id
```

Try to increase the timeout values by tuning `max_statement_time`, `max_execution_time`, `net_read_timeout`, `net_write_timeout` session parameters to the list of `session_sql` optional parameter to your [tap-mysql YAML file](https://transferwise.github.io/pipelinewise/connectors/taps/mysql.html#configuring-what-to-replicate):

MySQL:
```
db_conn:
  # <connection details>

  session_sqls:
    - SET @@session.max_execution_time=0     # No limit
    - SET @@session.net_read_timeout=3600    # 1 hour
    - SET @@session.net_write_timeout=3600   # 1 hour

    # Set other session variables to the default PPW ones
    - SET @@session.time_zone="+0:00"
    - SET @@session.wait_timeout=28800
    - SET @@session.innodb_lock_wait_timeout=3600
```
MariaDB:
```
db_conn:
  # <connection details>

  session_sqls:
    - SET SESSION max_statement_time=0      # No limit
    - SET SESSION net_read_timeout=3600.    # 1 hour
    - SET SESSION net_write_timeout=3600.   # 1 hour

    # Set other session variables to the default PPW ones
    - SET SESSION time_zone="+0:00"
    - SET SESSION wait_timeout=28800
    - SET SESSION innodb_lock_wait_timeout=3600
```

**Comment by amigold** [comment]
I think the real problem here is that there is no LIMIT
so if an incremental update is big enough, it will crash no matter what

**Comment by amigold** [comment]
This is what we are encountering now

**Comment by Samira-El** [comment]
Hey @amigold, 

Running Incremental without limit is by design, as Peter suggested above, you need to play with the various timeout session params to figure what works for the source DB.

You can try indexing the column that is used as replication key to speed up the queries and run the pipeline as frequently as possible to keep up with the source changes and get smaller query result.

**Comment by amigold** [comment]
Thanks @Samira-El after meditating on it a bit I realized that's indeed the correct way :)

**Comment by nauxliu** [comment]
I encountered the same issue, I've set the session parameters, and the init sync is still failing, sometime after 7 minutes after starting, sometimes after 40 minutes.

```
db_conn:

  session_sqls:
    - SET SESSION max_execution_time=0     # No limit
    - SET SESSION net_read_timeout=36000    # 1 hour
    - SET SESSION net_write_timeout=36000   # 1 hour

    # Set other session variables to the default PPW ones
    - SET SESSION time_zone="+0:00"
    - SET SESSION wait_timeout=288000
    - SET SESSION innodb_lock_wait_timeout=36000
```
