### ISSUE TITLE
Update docs to note mysql log replication schema change behaviour

### ISSUE THREAD

**Issue by EamonKeane** [transferwise/pipelinewise#505]
From reading the updates, it appears that mysql schema changes with log replication no longer require manual intervention, great work if so! It might be worth updating the docs as this is a key improvement on what Stitch have.

https://transferwise.github.io/pipelinewise/concept/replication_methods.html?highlight=log%20based%20replication

> Log Based replication method is available only for MySQL and PostgreSQL-backed databases that support binary log replication and requires manual intervention when table structures change.

**Comment by Samira-El** [comment]
Hey Eamon, indeed, we've added this feature just recently to avoid data loss when new columns are created or existing ones are renamed.

Thanks for pointing out this, will update the doc asap.
