### ISSUE TITLE
Fast-sync partial loading of table Mysql-Snowflake

### ISSUE THREAD

**Issue by EamonKeane** [transferwise/pipelinewise#511]
### Subject of the issue
I'm seeing some odd behaviour. For tables that are set to load fully every time (`FULL_TABLE`) I see at least one occassion where only a number of the rows are added into snowflake (e.g. 350/7500) but the process exits successfully.

In debug mode the number of rows copied from mysql and written to the file is correct (7500), but the number of rows loaded into snowflake is not (350). Have you ever experienced this behaviour? An additional check for fast-sync that verified that the number of rows loaded equalled the number written to the file should reveal when this happens.

This happens when loading multiple taps of the same source schema (mysql), perhaps it something to do with multiple files with same name (just different end timestamp prefix) open at same time. Perhaps replacing `time.strftime` second precision with microsecond `datetime.now().strftime("%Y%m%d-%H:%M:%S.%f")` would avoid this or ideally also add the tap id to be certain.

### Your environment
* Version 0.20.0
* Mysql
* Snowflake

### Steps to reproduce
Continually re-load small fast-sync tables from multiple different mysql instances (same schema) and check if the number of rows extracted and loaded are the same.

### Expected behaviour
Number of rows loaded is the same each time

### Actual behaviour
Table is only partially loaded

**Comment by Samira-El** [comment]
Hey, thanks for raising this issue.

We will try to reproduce it and get back to you.

Can you share the DDL of the table you're having issues with and also examples of how your taps are configured?

**Comment by koszti** [comment]
>This happens when loading multiple taps of the same source schema (mysql), perhaps it something to do with multiple files with same name (just different end timestamp prefix) open at same time. Perhaps replacing time.strftime second precision with microsecond datetime.now().strftime("%Y%m%d-%H:%M:%S.%f") would avoid this or ideally also add the tap id to be certain.

Interesting case. The uniqueness of the file names and the parallel running taps should not be the problem, otherwise the second tap should fail with `No such file or directory` when it's trying to delete the CSV from `~/.pipelinewise/tmp`. If both taps are using the same file then the first one should delete the file and the second should fail with error. Is this what you can see or all the taps finishing successfully?

**Comment by EamonKeane** [comment]
@koszti thanks for the reply. I have indeed also seen a fair bit of `no such file or directory`. I also think there is a clash on the s3 key. Both issues seem to have gone away after I added microseconds to the fast-sync s3 key and the local file.

**Comment by Samira-El** [comment]
Hi @EamonKeane,

This issue has been open for a while, is it still happening, is it a bug or mis-configuration?

**Comment by EamonKeane** [comment]
hi, it hasn't happened to my knowledge since I added my microsecond fix, I'll close the issue, you can reopen if you like.
