### ISSUE TITLE
PG Logical replication; override wal_sender_timeout value

### ISSUE THREAD

**Issue by lucaswiley** [transferwise/pipelinewise#513]
### Subject of the issue
Is there a way to override `wal_sender_timeout` for `tap_postgres` where replication_method = "LOG_BASED" ? I have a pipeline that is continuing to 
```
time=2020-08-26 00:38:17 logger_name=tap_postgres log_level=INFO message=Waiting for first wal message
time=2020-08-26 00:38:27 logger_name=tap_postgres log_level=INFO message=Waiting for first wal message
time=2020-08-26 00:38:37 logger_name=tap_postgres log_level=INFO message=Waiting for first wal message
time=2020-08-26 00:38:47 logger_name=tap_postgres log_level=INFO message=Waiting for first wal message
time=2020-08-26 00:38:57 logger_name=tap_postgres log_level=INFO message=Waiting for first wal message
time=2020-08-26 00:39:07 logger_name=tap_postgres log_level=INFO message=Waiting for first wal message
```
for up to 3 hours and then killing itself due to the conditions [here](https://github.com/transferwise/pipelinewise-tap-postgres/blob/master/tap_postgres/sync_strategies/logical_replication.py#L504). I think this is happening because it has been a while since the last message was received, due to issues related to https://github.com/transferwise/pipelinewise/issues/504. 

I would like to override this value such that I can get the LSN up to date for subsequent runs. Using manual runs of `pipelinewise sync_tables --target <target_id> --tap <tap_id>` enables me to do manual backfill using fastsync, but regular scheduled runs on Airflow are now failing due to the timeout. 

### Your environment
- PipelineWise 0.20.2 - Command Line Interface
- Tap Postgres
- Target Snowflake

### Steps to reproduce
Trigger normal run of pipelinewise pipeline, however you would need it to run for up to 3 hours while waiting for the first wal message. 

### Expected behaviour
Configure option to allow to run longer than 3 hours. 

### Actual behaviour
Pipeline times out after 3 hours due to restraint here: https://github.com/transferwise/pipelinewise-tap-postgres/blob/master/tap_postgres/sync_strategies/logical_replication.py#L504

### Further notes
I think that i let this pipeline sit for too long while I was working internally to resolve bad data inputs related to https://github.com/transferwise/pipelinewise/issues/504. While I did fix the issue internally, because of how long it took, my assumption is that enough data has piled up on the postgres WAL that it will require the pipeline more than 3 hours to run in order to get back up to date.

**Comment by koszti** [comment]
https://github.com/transferwise/pipelinewise-tap-postgres/blob/master/tap_postgres/sync_strategies/logical_replication.py#L530
I think it's not bacause of the `wal_sender_timeout` but because the `logical_poll_total_seconds` timeout [here](https://github.com/transferwise/pipelinewise-tap-postgres/blob/master/tap_postgres/sync_strategies/logical_replication.py#L530)

You can customise the `logical_poll_total_seconds` option in the tap YAML. This is currently undocumented but works:

```
db_conn:
  host: "<HOST>"
  port: 5432
  user: "<USER>"
  password: "<PASSWORD>"
  dbname: "<DB_NAME>"
  logical_poll_total_seconds: 43200   # default is 10800 3 hours
```

Btw, is there any data changes in your postgres DB since the last fastsync? That's also possible that no data changes in PG, basically everything up to data and it's just waiting for the first CDC event.

**Comment by lucaswiley** [comment]
Yes, if logical_poll_total_seconds is configurable, that would also solve the problem! 

With regard to your question, there are definitely data changes on the DB, as we have a fairly high velocity of data. My hypothesis is that because we had a failure in replication a few weeks ago that was only partially resolved until last week, the LSNs were not properly updating...so we need to scan the WAL for several hours in order to find the most up to date record.

**Comment by lucaswiley** [comment]
May I ask, do you have an idea of what other options are configurable in the YAML but are not documented?

**Comment by koszti** [comment]
`max_run_seconds`, `logical_poll_total_seconds`, and `break_at_end_lsn` configurable options were missing from the documentation.

PR https://github.com/transferwise/pipelinewise/pull/515 added it and it's now documented in the online docs and in the sample YAML files as well at https://transferwise.github.io/pipelinewise/connectors/taps/postgres.html#configuring-what-to-replicate
