### ISSUE TITLE
Change exit code to failure when tap already running

### ISSUE THREAD

**Issue by EamonKeane** [transferwise/pipelinewise#523]
### Subject of the issue
When using airflow with pipelinewise, occassionally a `*.pid` file or log file `*.running` is left over from a previous run for whatever reason (k8s node killed etc). When a subsequent run is triggered by airflow, this exits successfully and the dag proceeds even though the pipelinewise task has not succeeded. The suggested change would be to error and exit. A nice additional option would be a `--cleanup` flag to clean up any existing pid or running log files.

> pipelinewise.py line_no=(906) message=Tap ... is currently running. Do nothing and exit normally.

**Comment by timreimherr** [comment]
I'm running into this issue as well.
@EamonKeane have you found a workaround for this issue?

**Comment by koszti** [comment]
The original idea of returning 0 and not an error, when the tap started but another instance is still running was to avoid too many error message by frequent schedules or overlapping tap runs.

For example if we make this change and your tap scheduled to run every 10 minutes but the tap is normally running for 1 hour, then you will receive 5 error messages in 1 hour. What do you think, would that be still OK?

**Comment by EamonKeane** [comment]
I understand the reasoning @koszti , but I think changing the behaviour would be fine. Most people using pipelinewise would be using it in a batch oriented fashion once or twice a day. The risk with this current behaviour is that people don't catch this and they proceed to their transformations with missing data. Without additional checks in place, and assuming a previous abrupt exit (with lingering `*.pid` or `*.running`), a data pipeline could continue for several days before anyone noticed that it wasn't loading.

@timreimherr I have a `dbt source snapshot-freshness` step after pipelinewise runs which picks up whether the data source has up to date data.

**Comment by koszti** [comment]
fixed by https://github.com/transferwise/pipelinewise/pull/546 and released as part of PipelineWise 0.24.1
