### ISSUE TITLE
feature: generate valid PostgreSQL replication slot name when db name has invalid chars

### ISSUE THREAD

**Issue by hgrsd** [transferwise/pipelinewise#529]
When using logical replication from a PostgreSQL tap, the name of the replication slot used to read the WAL is automatically generated based on the database name and tap name. See [this piece of code](https://github.com/transferwise/pipelinewise-tap-postgres/blob/c0eb14ebfe14b10ad208d10c5d1d7f1bf5b8be25/tap_postgres/sync_strategies/logical_replication.py#L402). 

We have run into issues because some of our source databases had names that include a hyphen `-`, which is not allowed in the replication slot name.

More generally, the issue is that the set of characters allowed in Postgres database does not match the set of characters allowed in replication slot names (i.e. `[a-z0-9_]`).

Possible solutions:
- replace invalid characters either by an underscore or their unicode code point (see an example of this [here](https://github.com/zalando/patroni/pull/277))
- allow user to specify replication slot name as part of the `tap.yaml` configuration

The first option is probably simplest to implement. I would be happy to work on this and open a PR.

Looking forward to hearing what you think. Thanks in advance!

**Comment by koszti** [comment]
hey, thanks for this. Option one sounds like the best option: ubderscores, lowercase and trunc to max 64 chars similar to the patroni example.

Can you please send a PR? I’m sure we can merge that quickly.

Can you please make sure to add a few new test cases as well to cover ? You can find examples at https://github.com/transferwise/pipelinewise/blob/6be4ee8e4ea8096deb955f823cf6ca81476135e1/tests/units/fastsync/commons/test_fastsync_tap_postgres.py#L35

**Comment by koszti** [comment]
One more thing: we need to make sure that ppw-tap-postgres behaves the same here at https://github.com/transferwise/pipelinewise-tap-postgres/blob/c0eb14ebfe14b10ad208d10c5d1d7f1bf5b8be25/tap_postgres/sync_strategies/logical_replication.py#L402

Can you please send PR to tap-pg as well with the same change?

**Comment by hgrsd** [comment]
Thank you @koszti for your reply. I've opened two PRs as per your suggestion; let me know if you want any more work to be done on them.

**Comment by sroze** [comment]
Out of interest @koszti, do you have any plan to prevent/reduce this duplicated code?

**Comment by koszti** [comment]
fully fixed and released as part of 0.23.0 

@sroze, you're right and would be nice to remove duplicated codes. Maybe a common shared lib would do the trick but unfortunately that's not very straightforward and requires more investigation and planning. But yeah, stay tuned please;)
