### ISSUE TITLE
Properties.json not generating in full, leaving invalid JSON

### ISSUE THREAD

**Issue by lucaswiley** [transferwise/pipelinewise#533]
### Subject of the issue
What would cause a `properties.json` file e.g. `.pipelinewise/snowflake/postgres_dataobject/properties.json` to be generated as an invalid json?

I have verified the tap configuration file is valid YAML. But upon running the import config command I get: 
```
(pipelinewise) airflow@ip-172-31-30-223:~/onedrop-scripts/ingestion/pipelines$ pipelinewise import --dir /home/airflow/onedrop-scripts/ingestion/pipelines --secret /home/airflow/onedrop-scripts/ingestion/pipelines/vault-password.txt
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.config log_level=INFO message=Searching YAML config files in /home/airflow/onedrop-scripts/ingestion/pipelines
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.config log_level=INFO message=LOADING TARGET: target_snowflake.yml
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.config log_level=INFO message=LOADING TAP: tap_postgres_main.yml
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.config log_level=INFO message=LOADING TAP: tap_postgres_dataobject.yml
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.config log_level=INFO message=SAVING CONFIG
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.config log_level=INFO message=SAVING MAIN CONFIG JSON to /home/airflow/.pipelinewise/config.json
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.config log_level=INFO message=SAVING TARGET JSONS to /home/airflow/.pipelinewise/snowflake/config.json
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.config log_level=INFO message=SAVING TAP JSONS to /home/airflow/.pipelinewise/snowflake/postgres_main
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.config log_level=INFO message=SAVING TAP JSONS to /home/airflow/.pipelinewise/snowflake/postgres_dataobject
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=ACTIVATING TAP STREAM SELECTIONS...
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Discovering postgres_main (tap-postgres) tap in snowflake (target-snowflake) target...
time=2020-09-21 17:41:33 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Discovering postgres_dataobject (tap-postgres) tap in snowflake (target-snowflake) target...
time=2020-09-21 17:41:36 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Writing new properties file with changes into /home/airflow/.pipelinewise/snowflake/postgres_main/properties.json
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    3.2s
Traceback (most recent call last):
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/pipelinewise/cli/utils.py", line 87, in load_json
    return json.load(jsonfile)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 14621 column 36 (char 508669)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/.virtualenvs/pipelinewise/bin/pipelinewise", line 33, in <module>
    sys.exit(load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')())
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/pipelinewise/cli/__init__.py", line 160, in main
    getattr(ppw_instance, args.command)()
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/pipelinewise/cli/pipelinewise.py", line 1204, in import_project
    ) for tap in target.get('taps')))))
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/.virtualenvs/pipelinewise/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/.virtualenvs/pipelinewise/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/.virtualenvs/pipelinewise/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/.virtualenvs/pipelinewise/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/.virtualenvs/pipelinewise/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/pipelinewise/cli/pipelinewise.py", line 676, in discover_tap
    old_schema = utils.load_json(tap_properties_file)
  File "/home/airflow/onedrop-scripts/ingestion/pipelinewise/pipelinewise/cli/utils.py", line 92, in load_json
    raise Exception(f'Error parsing {path} {exc}')
Exception: Error parsing /home/airflow/.pipelinewise/snowflake/postgres_dataobject/properties.json Expecting ':' delimiter: line 14621 column 36 (char 508669)
```

When I inspect ` /home/airflow/.pipelinewise/snowflake/postgres_dataobject/properties.json`, the tail of the file does not complete the JSON generation and ends abruptly as invalid JSON: 

```
...
,
                {
                    "breadcrumb": [
                        "properties",
                        "activityEndDate"
                    ],
                    "metadata": {
                        "inclusion": "available",
                        "selected-by-default": true,
                        "sql-datatype": "timestamp with time zone"
                    }
                },
                {
                    "breadcrumb": [
                        "properties",
                        "activityStartDate"
                    ],
                    "metadata": {
                        "inclusion"
```

### Your environment
* PipelineWise 0.22.1 - Command Line Interface -- commit 41aee87333897660cfa56e949ca77b9f3278fff8
* Tap postgres
* Target snowflake

### Steps to reproduce
You would need to replicate my configuration files and then import them using `pipelinewise import`

### Expected behaviour
I'm not sure, i would expect the `/properties.json` to be fully generated. 

### Actual behaviour
`/properties.json` is not fully generated and therefore it throws a parsing error. 

### Further notes
I've tried pulling the most recent changes from Pipelinewise, I've reinstalled pipelinewise, I've commented out various parts of the configuration file. No clear answer yet.

**Comment by lucaswiley** [comment]
Additionally, I'm noticing that not all the tables specified in the tap configuration file are being recognized and do not appear in the `properties.json` file, however they do appear in the source database. 

I reran the configuration import command but these tables still do not show up in the `properties.json`.

**Comment by lucaswiley** [comment]
Hi, just wanted to follow up here. Specifically on the notion that new tables added to the pipeline config files are not showing up in the actual pipeline runs.

**Comment by Samira-El** [comment]
Hey Lucas,

The not fully-generated properties problem could indeed be due to parallel running imports, we haven't had this problem .. yet, but, will investigate more once we have time.

re new tables not added to the pipeline config, can you please check the `selection.json` file if it contains those new tables after running import? 
If no, please delete the config files and run import again. Otherwise, if `properties` file doesn't contain these tables, please run this [query](https://github.com/transferwise/pipelinewise-tap-postgres/blob/a1f299f6354070665120f11d79f655e55d04010f/tap_postgres/discovery_utils.py#L69) against your DB and see if the tables show up in the result.

Let me know how it goes.

**Comment by lucaswiley** [comment]
Hi Samira,

Thanks for your response. I verified the following:
- The tables do show in the `selection.json`, which just looks like a compiled json version of the config file itself. 
- The tables do not appear in `properties.json`
- I ran the query and did verify that yes these tables do exist in the source db. 

I additionally tried deleting the configs and recreating them as new files. This did not resolve the issue. Is there by chance a table limit on how many tables can be compiled from the yml config? It does seem odd that it's only newer tables that are missing from this config properties file.

Thanks

**Comment by lucaswiley** [comment]
@Samira-El I just double checked this is happening for all tap config files. I also updated to the most recent changes from pipelinewise to be sure and this is still an issue. I wonder if it could be something to do with the replication slot...but I'm not sure why the records would show up in `selection.json` but not in `properties.json`

**Comment by lucaswiley** [comment]
I filed a separate ticket for this https://github.com/transferwise/pipelinewise/issues/549, as this new issue is likely being masked by the title of this one and this is somewhat high urgency. Thank you Samira!
