### ISSUE TITLE
New tables not replicating; Properties.json not reflecting tables in configuration file

### ISSUE THREAD

**Issue by lucaswiley** [transferwise/pipelinewise#549]
**Describe the bug**
When I add new tables to postgres configuration files, these tables do show up in `selection.json`, but do not show up in `properties.json`. This means the tables are not replicated at all. These tables do exist in the source database. 

**To Reproduce**
1. Add new tables to `tap-postgres` config file. 
2. Run `pipelinewise import --dir ... --secret ...`
2. Run the pipeline either normally or with fastsync (`run_tap` or `sync_tables`)
4. Do not see new tables in `properties.json`, pipeline process log file, or in Snowflake DW. 

**Expected behavior**
See new tables being replicated in `properties.json`, log file, and Snowflake. 

**Screenshots**
Add new table "diagnosis" to tap-postgres config. 
<img width="834" alt="Screen Shot 2020-10-07 at 8 09 12 AM" src="https://user-images.githubusercontent.com/22181786/95350970-917cc080-0875-11eb-89e2-44d7de929967.png">

See table in `selection.json`
<img width="382" alt="Screen Shot 2020-10-07 at 8 16 45 AM" src="https://user-images.githubusercontent.com/22181786/95351472-1cf65180-0876-11eb-99c6-73d328b029a4.png">

Do not see table in `properties.json` or log file (shown here). 
<img width="1583" alt="Screen Shot 2020-10-07 at 8 09 43 AM" src="https://user-images.githubusercontent.com/22181786/95351355-fe905600-0875-11eb-8141-4c0a8b08b823.png">

**Your environment**
 - PipelineWise 0.22.1 - Command Line Interface [@41aee](https://github.com/transferwise/pipelinewise/tree/41aee87333897660cfa56e949ca77b9f3278fff8)
 - tap postgres
 - target snowflake

**Additional context**
This has somewhat high urgency as we cannot replicate new tables currently. I have tried wiping the config files entirely and recreating them but this did not resolve it. I also ensured to re-install pipelinewise to latest version.

**Comment by Samira-El** [comment]
Can you run import with `--debug` and share the output?

**Comment by lucaswiley** [comment]
[Uploading import_output.txt…]()


A few tables that I would expect to see here but do not are `diagnosis`, `dataobject_y2020m09`, and a few others.

**Comment by koszti** [comment]
It's also possible that pipelinewise doesn't have all the required access to the table, the tables not visible to the PPW user and it doesn't put the new tables into `properties.json`. I've seen this once earlier.

Can you please try to run the discovery SQL directly in the source system with the same user that you use in pipelinewise? Can you see the new tables in the SQL output?
The discovary SQL is available at https://github.com/transferwise/pipelinewise-tap-postgres/blob/fe5493b1b03ee24b6dc845200cb270f9a8c7b671/tap_postgres/discovery_utils.py#L69

Also please make sure you don't use the `filter_schemas` option in the YAML config or the schema of the new tables listed in `filter_schemas`.

**Comment by lucaswiley** [comment]
@koszti Looks like you are exactly right Peter. Thanks for calling this out. I updated the permissions in the source database and now the tables are showing up in the pipelinewise logs. 

Question, do you think it makes sense to include the following line in the SQL setup for the tap-postgres install documentation? This would set default privileges on future tables that do not yet exist.
`alter default privileges in schema public grant all on tables to pipelinewise;`
https://transferwise.github.io/pipelinewise/connectors/taps/postgres.html

Thank you both for calling this out, did not cross my mind 🤦

**Comment by Samira-El** [comment]
I'm glad it's working for you now! Thanks @koszti for the great insight!

That sounds like a great suggestion, I've created a [PR](https://github.com/transferwise/pipelinewise/pull/551)
Does it look good?

**Comment by Samira-El** [comment]
PR merged.
