### ISSUE TITLE
Add documentation that clarifies license relationship between pipelinewise and taps 

### ISSUE THREAD

**Issue by DuaneOBrien** [transferwise/pipelinewise#558]
**Is your feature request related to a problem? Please describe.**
The documentation doesn't appear to contain any explanation of the relationship between Pipelinewise licenses and the licenses of the taps. Because pipelinewise is licensed Apache 2, and the taps each have a range of licenses including AGPL, it's not immediately obvious what obligations end users have when they make local changes to pipelinewise, and then consume a tap with a license that is incompatible with Apache 2.

**Describe the solution you'd like**
Add clear documentation describing the interrelationship between pipelinewise and any taps that are consumed. Specifically:
* If Pipelinewise uses a tap that is licensed AGPL, does pipelinewise inherit the AGPL license?
* If so, why? If not, why not? 
* If an end user makes a local modification to pipelinewise, and pipelinewise inherits a license from a tap, what obligations does the user have to make the modification available, and to whom?

By clearly and publicly documenting the guidance around license interaction between pipelinewise and taps, we can avoid users unintentionally falling under license obligations of which they are not aware, and make it easier for organizations to know what the implications of the license interaction are.

**Describe alternatives you've considered**
Short of each end user securing legal counsel from an expert in open source licensing to render an opinion, I'm not aware of an alternative.

**Additional context**
I wasn't able to find any clear discussion or documentation elsewhere about the subject, but you can see some discussion of the issues related to this concern here: https://gitlab.com/meltano/meltano/-/issues/94

**Comment by koszti** [comment]
fair point, we need to clarify and add a new section to the doc.

The final license depends on which tap and target connectors you use into the final pipelinewise build. If you use PPW only with Apache2 connectors then the entire software package is Apache2 licensed. If you use at least one AGPL connector then AGPL license is applied for the whole package.

**Comment by uncle9999** [comment]
https://github.com/transferwise/pipelinewise-target-s3-csv/pull/29#issue-495485048

**Comment by koszti** [comment]
Added License section to the documentation [here](https://transferwise.github.io/pipelinewise/project/licenses.html).

I hope this helps.
