### ISSUE TITLE
Error in Dockerfile when adding tap-oracle

### ISSUE THREAD

**Issue by nugic** [transferwise/pipelinewise#570]
**Describe the bug**
In Dockerfile the following line is executed when tap-oracle is chosen:

RUN bash -c "if grep -q \"tap-oracle\" <<< \"$connectors\"; then wget https://download.oracle.com/otn_software/linux/instantclient/193000/oracle-instantclient19.3-basiclite-19.3.0.0.0-1.x86_64.rpm -O /app/oracle-instantclient.rpm && alien -i /app/oracle-instantclient.rpm --scripts && rm -rf /app/oracle-instantclient.rpm ; fi"

This tries to download oracle-instantclient to /app folder but this doesn't exist yet.

**To Reproduce**
1. Run docker build as:
docker build --build-arg connectors=tap-oracle,target-snowflake -t pipelinewise:latest .
2. See error

**Expected behavior**
Finished build with no errors.

**Your environment**
 - Pipelinewise v0.24.1

**Proposed solution**
Download oracle-instantclient to /tmp folder instead or create /app folder before.

**Comment by koszti** [comment]
thanks, for reporting.
Fixed by https://github.com/transferwise/pipelinewise/pull/572
