### ISSUE TITLE
Partial record counts captured by pipelinewise while performing deletes

### ISSUE THREAD

**Issue by snehamitta** [transferwise/pipelinewise#587]
### Subject of the issue
On deleting records from MySQL and running pipelinewise with log_based replication at the same time, not all deleted records are captured by pipelinewise, only a subset of the deleted records are marked as deletes and exported to Snowflake. Though the log_file and the log_position written to state file at the end of the run are the start point for the next pipelinewise run, do not capture the missed records from the previous run.

### Your environment
**Tap:** tap-mysql
batch_size_rows: 80000
add_metadata_columns: True
hard_delete: False

**MySQL Binlog Configuration**: Configured the binlog parameters as suggested in the documentation for MySQL log based replication 

**Target**: target-snowflake

### Steps to reproduce
I am unable to reproduce this issue consistently, but as a part of performing deletes on tables in MySQL and exporting to snowflake using pipelinewise, I've encountered this scenario multiple times. 

SQL Statements used to delete records in MySQL: 
delete from table_a where table_a.row_num >= 1 and table_a.row_num <= 28764;
delete from table_b where table_b.row_num >= 1 and table_b.row_num <= 5438;
delete from table_c where table_c.row_num >= 1 and table_c.row_num <= 10925;
delete from table_d where table_d.row_num >= 1 and table_d.row_num <= 128998;
delete from table_e where table_e.row_num >= 1 and table_e.row_num <= 595548;

### Example of Actual Behaviour
In my pipeline, I have 5 tables, all set to log_based replication and I'd like to perform deletes on all 5 tables. I queue up the delete statements to run and start my pipelinewise job immediately. This pipelinewise run finishes successfully and only captured deletes on the first 3 tables. On scanning the pipelinewise log for this run, the first 2 tables in the delete sequence are working as expected, but for the 3rd table only 68 records are marked as deletes and exported to snowflake when the actual count of deletes on this table was 10925.

I run the pipelinewise job again after all deletes on MySQL are complete, expecting it to pick up records missed from the 3rd table. The new pipelinewise job only captures deletes of the last 2 tables, completely missing the records left out from the previous run on the 3rd table.

**Comment by Samira-El** [comment]
Hey Sneha,

Thanks for reporting this issue!
We will investigate and try to reproduce this issue, will keep you updated.

**Comment by Samira-El** [comment]
Hi,
To give an update on this, this is indeed an bug, however, the bug is in a third party library used in `pipelinewise-tap-mysql` to fetch the changes from binlog files: https://github.com/noplay/python-mysql-replication . You can find similar issues that have been reported in the that repo about missing data. 

Currently, there are no alternative libraries to use to read the binlogs, but we are thinking of a workaround, which could affect the performance of the extraction.

Will keep you posted if there are any updates.

**Comment by Samira-El** [comment]
Hey,

We have deployed a fix for this in the latest release.
Feel free to try it out and let me know if you're still facing the same problem by raising another issue.

Closing this.
