### ISSUE TITLE
Broken Pipe error

### ISSUE THREAD

**Issue by ayhanaltunkaynak** [transferwise/pipelinewise#591]
**Hi, 

We have been using Pipelinewise to sync data from MySQL to Snowflake using a log-based replication method. However, the sync broke suddenly with a broken pipe error. We couldn't recover it until we force it to do full table sync. After the fast-sync is done it could continue to do log-based replication again. We are wondering about the possible reasons and solutions instead of replicate everything from scratch. Please advise.

`Traceback (most recent call last):
  File "/app/.virtualenvs/target-snowflake/bin/target-snowflake", line 8, in <module>
    sys.exit(main())
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 446, in main
    persist_lines(config, singer_messages, table_cache)
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 189, in persist_lines
    adjust_timestamps_in_record(o['record'], schemas[stream])
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 150, in adjust_timestamps_in_record
    reset_new_value(record, key, schema['properties'][key]['format'])
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 136, in reset_new_value
    parser.parse(record[key])
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not int
time=2020-12-11 14:54:29 logger_name=singer log_level=INFO message=METRIC: {"type": "timer", "metric": "job_duration", "value": 2.170612096786499, "tags": {"job_type": "sync_binlog", "status": "failed"}}
time=2020-12-11 14:54:29 logger_name=tap_mysql log_level=CRITICAL message=[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/app/.virtualenvs/tap-mysql/bin/tap-mysql", line 8, in <module>
    sys.exit(main())
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 712, in main
    raise exc
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 709, in main
    main_impl()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 702, in main_impl
    do_sync(mysql_conn, args.config, catalog, state)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 654, in do_sync
    sync_binlog_streams(mysql_conn, binlog_catalog, config, state)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 646, in sync_binlog_streams
    binlog.sync_binlog_stream(mysql_conn, config, binlog_catalog.streams, state)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/sync_strategies/binlog.py", line 440, in sync_binlog_stream
    _run_binlog_sync(mysql_conn, reader, binlog_streams_map, state)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/sync_strategies/binlog.py", line 360, in _run_binlog_sync
    time_extracted)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/sync_strategies/binlog.py", line 255, in handle_write_rows_event
    singer.write_message(record_message)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/singer/messages.py", line 227, in write_message
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

-------------------------------------------------------
TAP RUN SUMMARY
-------------------------------------------------------
    Status  : FAILED
    Runtime : 0:22:35.443356
-------------------------------------------------------`
**

**Comment by mashanm** [comment]
+1

**Comment by Samira-El** [comment]
Hey,

It seems like target-snowflake has received a record where some date field is not string but an int and thus failed to be parsed.
Can you perhaps share the DDL or the json schema of the table that you're syncing?

**Comment by ayhanaltunkaynak** [comment]
Hi,

Once we have the error we tried to narrow down the error in a table-level by manipulating the state.json file. We removed the tables one by one in order to force them to fast sync. Each time, the LOG-BASED sync failed until we remove the last table from the state.json file. I cannot share the table structures. But see the column types below. Could it be related to the time column type?

```
varchar
datetime
int
bit
bigint
longtext
tinyint
char
date
double
mediumtext
text
float
time
timestamp
```

**Comment by ayhanaltunkaynak** [comment]
It happened again. But this time the error says the problematic value.

```snowflake.connector.errors.ProgrammingError: 100038 (22018): Numeric value '2021-01-19T17:23:55+00:00' is not recognized```

**Comment by Samira-El** [comment]
Hey,
Haven't had the time to investigate this further.
That is a different error to the original one, it is clearly complaining that it's expecting a numeric type value but it got a stringified date, has the type of the column changed in the source?

**Comment by ayhanaltunkaynak** [comment]
No there are no data type changes happened but we added a new column by specifying the location of the column. May it cause the problem?

**Comment by Samira-El** [comment]
What do you mean by _specifying the location of the column._ ? Can you please elaborate? Also, what's the type of this column?

**Comment by ayhanaltunkaynak** [comment]
> What do you mean by _specifying the location of the column._ ? Can you please elaborate? Also, what's the type of this column?

The newly added column type is bigint. You know in MySQL you can add a column in a specific location using FIRST or AFTER statement. In our case, the new column has been added next to the first column of the table.
i.e:
`ADD [COLUMN] column_name column_definition [FIRST|AFTER existing_column];`

**Comment by Samira-El** [comment]
Thank you.
This shouldn't be a problem, it doesn't matter how  column was added.

Can you share the type of this column?

**Comment by ayhanaltunkaynak** [comment]
if you excuse me I can share the table structure by only anonymizing the column names.

```
Field | Type
-- | --
Column1 | bigint(20) unsigned
Column2 | bigint(20) unsigned
Column3 | bigint(20) unsigned
Column4 | bigint(20) unsigned
Column5 | varchar(200)
Column6 | varchar(17)
Column7 | varchar(14)
Column8 | varchar(14)
Column9 | date
Column10 | char(20)
Column11 | varchar(50)
Column12 | tinyint(1)
Column13 | tinyint(1)
Column14 | int(11)
Column15 | datetime
Column16 | datetime
Column17 | datetime
Column18 | varchar(50)
Column19 | varchar(50)
Column20 | varchar(500)
Column21 | datetime
Column22 | datetime
```

**Comment by Samira-El** [comment]
Thank you for this but I wanted the type of the new column you added.

Also, tit would be very helpful if you could map each column type to its type in the target table you have in Snowflake. e.g:
```
field | type in source | type in target
------|--------------------|-------------------
column1 | bigint(20) unsigned | numeric
.
.
.
etc
```

**Comment by ayhanaltunkaynak** [comment]
Hi, 
The new column is column3 and its type is BIGINT. I removed the table from state.json and fast sync went well. However, the log-based synchronization keeps failing. The date value in the error also changed.

`snowflake.connector.errors.ProgrammingError: 100038 (22018): Numeric value '2021-01-19T07:09:55+00:00' is not recognized`

Please also find the table mapping below:

```

Field | Type in source | Type in Target
-- | -- | --
Column1 | bigint(20) unsigned | NUMBER(38,0)
Column2 | bigint(20) unsigned | NUMBER(38,0)
Column3 | bigint(20) unsigned | NUMBER(38,0)
Column4 | bigint(20) unsigned | NUMBER(38,0)
Column5 | varchar(200) | VARCHAR(16777216)
Column6 | varchar(17) | VARCHAR(16777216)
Column7 | varchar(14) | VARCHAR(16777216)
Column8 | varchar(14) | VARCHAR(16777216)
Column9 | date | TIMESTAMP_NTZ(9)
Column10 | char(20) | VARCHAR(16777216)
Column11 | varchar(50) | VARCHAR(16777216)
Column12 | tinyint(1) | BOOLEAN
Column13 | tinyint(1) | BOOLEAN
Column14 | int(11) | NUMBER(38,0)
Column15 | datetime | TIMESTAMP_NTZ(9)
Column16 | datetime | TIMESTAMP_NTZ(9)
Column17 | datetime | TIMESTAMP_NTZ(9)
Column18 | varchar(50) | VARCHAR(16777216)
Column19 | varchar(50) | VARCHAR(16777216)
Column20 | varchar(500) | VARCHAR(16777216)
Column21 | datetime | TIMESTAMP_NTZ(9)
Column22 | datetime | TIMESTAMP_NTZ(9)
_SDC_EXTRACTED_AT | - | TIMESTAMP_NTZ(9)
_SDC_BATCHED_AT | - | TIMESTAMP_NTZ(9)
_SDC_DELETED_AT | - | VARCHAR(16777216)
```

**Comment by Samira-El** [comment]
Thank you, do you perhaps know which column contains this date `'2021-01-19T07:09:55+00:00'`?

**Comment by ayhanaltunkaynak** [comment]
Yes, it is column 15. But I see the value as `2021-01-19 07:09:55` in the source DB.
--

**Comment by Samira-El** [comment]
Thank you.
Can you please try enabling record validation by having `validate_records: true` in your tap config file, it's target param so it needs to at the same level as say `batch_size_rows` property.
This will instruct the target to validate every record against the schema it has, it will affect performance but it will help figure out if the source is producing invalid records.

**Comment by ayhanaltunkaynak** [comment]
We enabled the parameter. But we also had to force the tables to fast sync to get rid of the missing binary log exception. After the fast sync completed successfully the log-based sync continues to working again.  I checked the log files but couldn't find anything useful. Because no error anymore.
