### ISSUE TITLE
Snowflake Target - Speeding up timing of merges/commits/deletes

### ISSUE THREAD

**Issue by cap-itadmin** [transferwise/pipelinewise#605]
I have a postgres tap to S3, with a Snowflake target. I am inserting batches of 250,000 records at a time, into Snowflake.

When I check Snowflake history, activity timing is as follows, with end times shown to the right.

Merge: 6.5 seconds (250,000 records) 7:38:42 AM
Commit: 41 ms 7:38:42 AM
Delete from target table where _sdc_deleted_at...: 357 ms 7:38:43 AM
Commit: 41 ms 7:38:43 AM

So - to round up, a 7 second batch. My question is why the next Snowflake cycle starts around 2 minutes 45 seconds later, at 7:41:30 AM, and can I adjust this wait time?

Thanks,
Karen

**Comment by Samira-El** [comment]
Hey Karen,

Target snowflake operates with batches, there is a config param `batch_size_rows`, the records that the target is receiving are kept in memory, once the `batch_size_rows` is reached, it's time to flush the memory and start the merge process.

You can have more frequent merges by decreasing the `batch_size_rows`, but Snowflake is more efficient when the size is big.

**Comment by cap-itadmin** [comment]
Hey Samira,

The batch_size_rows in the postgres yaml is set to 250,000,  My concern is keeping up with the data.  I will try increasing the batch size, but what else can I do to increase speed?

Snowflake warehouse size is XS.

Pipelinewise is running on an AWS m5a.2XL

Thank you for your help!
Best,
Karen

**Comment by Samira-El** [comment]
PipelineWise is not a real time engine, there would always be a lag of at least few minutes.

The speed depends on so many factors: resources of the infra, snowflake warehouse size, activity rate of the source db ..etc

You could try bumping the infra up and throwing more CPU at  Pipelinewise, Also consider scaling snowflake warehouse.
I don't know what your load is, so you gotta have to keep tinkering until you reach performances that you're happy with.

**Comment by cap-itadmin** [comment]
Got it, thanks.   Load for the table in question is about 2.4 million rows an hour.  Postgres columns are:

id (big serial)
d_id (text)
d_time(text)
duration (int4)
created_at (timestamptz)
modified_at (timestamptz)
d1 (jsonb)
d2 (jsonb)
d3 (jsonb)
d4(jsonb)
d5 (jsonb)
