### ISSUE TITLE
Considerations when stopping a tap

### ISSUE THREAD

**Issue by cap-itadmin** [transferwise/pipelinewise#632]
I have a postgres tap with a Snowflake target, which loads records in batches of 250,000 to Snowflake.

What do I need to take into consideration, when stopping the tap?  Do I need to time it for after the Snowflake COMMIT or will pipelinewise cleanly complete the current batch and then stop?

Thanks!
Karen

**Comment by Samira-El** [comment]
Hey,

Stopping a tap sends a signal to gracefully kill the running pipeline immediately, unfortunately, that means any current batch/processes are gonna be terminated.
