### ISSUE TITLE
Unable to turn off hard_delete (Snowflake Target, Postgres Tap)

### ISSUE THREAD

**Issue by cap-itadmin** [transferwise/pipelinewise#693]
**Describe the bug**
Pipelinewise is not respecting the settings in target yml file for hard_delete= False. 
Rows in Snowflake are being deleted vs. flagged as marked for deletion.

**To Reproduce**
1. For an existing Postgres tap - Snowflake target pipeline, delete rows in tap database table and then run the pipeline.
2. Confirm rows are deleted in target Snowflake table.

**Expected behavior**
I would expect the _SDC_DELETED_AT column to be populated.  Instead, the rows are deleted in Snowflake.

**Screenshots**
![image](https://user-images.githubusercontent.com/34375254/114752584-760ed880-9d24-11eb-8233-7b7ee3510f02.png)

**Your environment**
Running in Docker
Source: Postgres
Target: Snowflake
Using Log Based Replication

**Additional context**

**Comment by Samira-El** [comment]
Hey,

`hard_delete` needs to be under `db_conn` property.

**Comment by cap-itadmin** [comment]
Thanks Samira-El - I will make the change.  It would be helpful to have the documentation updated to reflect this; apologies if I missed this.
