### ISSUE TITLE
Postgres interval becomes a  string in snowflake

### ISSUE THREAD

**Issue by ashalitkin** [transferwise/pipelinewise#781]
Hi there, I use pipelinewise to transfer data from postgres to snowflake and interval is saved as a string like e.g. '1 hour 3 min'. It's useless as interval is needed for different calculations. Ideally I'd like it to be saved as number of seconds. Is it a way to somehow add a custom transformation for this data type? 
Any workaround (except parsing on snowflake side) probably?

**Comment by Samira-El** [comment]
Hello @ashalitkin, interval data type is currently not supported and is not being mapped to any special Snowflake column type. I'm afraid there is no workaround for this if you're not open to parsing on Snowflake side.

Also, why would having this as seconds be ideal? you can make use of Snowflake's INTERVAL keyword to do any calculation with this column.

**Comment by ashalitkin** [comment]
Cool. Couldn't find about it in the official doc. It probably solves the issue

**Comment by Samira-El** [comment]
lmk how it goes :)

**Comment by Samira-El** [comment]
Can you close this issue if all is well?
