### ISSUE TITLE
Failure in Date parsing (PostgreSQL to Snowflake)

### ISSUE THREAD

**Issue by esenilsson** [transferwise/pipelinewise#791]
Hi,

**Issue**
This issue is related to https://github.com/transferwise/pipelinewise-target-snowflake/issues/102. I am using Postgres tap and Snowflake target. In the source there are dates that are not formatted properly (such as the example below "20107-05-10"). When running the pipeline, Snowflake will not load the data into a table, as it has inferred timestamp data type from Postgres.

**To Reproduce**
1. Prepare the data with a timestamp column, and one record with something like "20107-05-28"
2. Configure postgres-tap and snowflake tap. (validate_data = false, s3 encryption keys)
3. 3.Run the command pipeline import --dir folder, and then pipeline run_tap --tap postgres-tap-name --target snowflake-target-name

`sync.log
time=2021-08-31 13:00:24 logger_name=pipelinewise.cli.pipelinewise log_level=ERROR message=Command failed. Return code: 1
Error(s) found:
time=2021-08-31 13:00:24 logger_name=pipelinewise.fastsync.postgres_to_snowflake log_level=ERROR message=100035 (22007): Timestamp '20107-05-10' is not recognized
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
    Error.errorhandler_wrapper(
    cursor.errorhandler(connection, cursor, error_class, error_value)
snowflake.connector.errors.ProgrammingError: 100035 (22007): Timestamp '20107-05-10' is not recognized
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
            Exceptions during table sync   : ['public.invoice: 100035 (22007): Timestamp \'20107-05-10\' is not recognized\n  File \'pipelinewise_invoice_public.invoice_20210831-124814-740227_fastsync_K0Q9AFV6.csv.gz.part00001\', line 809091, character 21\n  Row 809091, column "INVOICE_TEMP"["ENDDATE":3]\n  If you would like to continue loading when an error is encountered, use other values such as \'SKIP_FILE\' or \'CONTINUE\' for the ON_ERROR option. For more information on loading options, please run \'info loading_data\' in a SQL client.']
`
**Expected behavior**
I will be able to mitigate this issue, by either:
- faulty date replaced by max_timestamp (as described in issue-102)
- Being able to manually infer data types and force it to varchar in Snowflake
- Being able to change COPY into command and ON_ERROR parameters

**Your environment**
 - Version of target: (pipelinewise-target-snowflake 1.13.1) (pipelinewise-tap-postgres 1.8.0)
 - Version of python 3.8

**Comment by Samira-El** [comment]
Hi @esenilsson, thanks for reporting this bug!
will look into it.

**Comment by Samira-El** [comment]
Hey @esenilsson, this should be fixed now, please try again and lmk how it goes.

**Comment by esenilsson** [comment]
Hey @Samira-El! It works fine now! Thanks a lot for getting back to me
