### ISSUE TITLE
Redshift End to End Tests not running

### ISSUE THREAD

**Issue by judahrand** [transferwise/pipelinewise#864]
**Describe the bug**
At the moment it seems that most or all Redshift End to End tests are skipped. Is this intentional? Is it due to a lack of testing infrastructure? Can this be put in place if so?

**Expected behavior**
The Redshift End to End tests should all run and pass.

**Comment by Samira-El** [comment]
Same as with bigquery, https://github.com/transferwise/pipelinewise/issues/863

**Comment by Samira-El** [comment]
Closing this.

**Comment by judahrand** [comment]
Do you think it would be worth pinning this issue? It isn't clear from the project / docs that certain parts of the codebase are unsupported and untested.
