### ISSUE TITLE
ujson.JSONDecodeError: Value is too big!

### ISSUE THREAD

**Issue by JustMaris** [transferwise/pipelinewise#960]
**Describe the bug**
After updating Pipelinewise to the current latest release - 0.44.0, some tables started failing to be synced with ujson.JSONDecodeError: Value is too big!

**To Reproduce**
I haven't pinpointed what part exactly in the table causes this error, but it is not present in 0.43.1

**Expected behavior**
All tables are succesfully synced, just like previously

**Error traceback**
```
`Traceback (most recent call last):
  File "/app/.virtualenvs/target-snowflake/bin/target-snowflake", line 8, in <module>
    sys.exit(main())
  File "/app/.virtualenvs/target-snowflake/lib/python3.8/site-packages/target_snowflake/__init__.py", line 526, in main
    persist_lines(config, singer_messages, table_cache, file_format_type)
  File "/app/.virtualenvs/target-snowflake/lib/python3.8/site-packages/target_snowflake/__init__.py", line 123, in persist_lines
    o = ujson.loads(line)
ujson.JSONDecodeError: Value is too big!`
```

**Your environment**
 - Pipelinewise version 0.44.0
 - tap-postgres
 - target-snowflake

**Additional context**
I think that this is related to bump in snowflake connector version, which probably also updated some constraints for ujson and some version of ujson has this issue.

**Comment by Samira-El** [comment]
This has been fixed.
