### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by podviaznikov** [transferwise/pipelinewise#971]
Hi!

I'm trying Pipelinewise 0.44. I'm tryin to sync data between PG and Snowflake.
I'm running pipelinewise as k8s job for now.

So far I tried to sync one table (users table, nothing fancy there). It has 24M records.
It takes approximately 35-40 mins to finish the job (initial sync, both FULL_TABLE and LOG_BASED modes).

I wanted to achieve faster times so I tried to play with different parameters:

 - fastsync_parallelism - set to 4 (also set k8s cpus to 4 and memory to 8GB)
 - batch_size_rows - tried setting it to 250000
 - stream_buffer_size 2500

However, none of those things changed initial sync time.

I also think based on logs that the biggest amount of time is fetching data from PG (and maybe 5 minutes loading it into Snowflake).

What else can I do to try sync job go faster? Also how would I profile where is bottle neck is?

**Comment by Samira-El** [comment]
The biggest time sink in initial sync from PG to SF is data extraction from PG (`COPY` query), none of those parameters are gonna help here, you could try scaling up your server. 

Pipelinewise cli has a profiler option `--profiler` or `-p` to turn on profiling, the results are files in a new folder called `profiling`

**Comment by podviaznikov** [comment]
@Samira-El I think I expected this answer. The fact that there are not many parameters that can help.

**Comment by podviaznikov** [comment]
@Samira-El I see that parallelization happens using CPU pool (https://github.com/transferwise/pipelinewise/blob/master/pipelinewise/fastsync/postgres_to_snowflake.py#L205), but it's per table.

So if I have 4 tables, I can add 4 CPU and 4 tables will be synced in parallel.

Do you know if it's possible at all to speed up or parallelize syncing of one huge table. I think it's not possible, but maybe you have some ideas how it's can be achieved theoretically.

**Comment by Samira-El** [comment]
No it's not possible, because it's exporting the data from PG that takes most time, it's a full scan of the the table, the bigger it is, the longer it will take.
Maybe you could look at the some tweaks from the DB/table side, but I'm no DBA so can't advise.

**Comment by podviaznikov** [comment]
thank you @Samira-El
